### PR TITLE
Add Simplified Chinese

### PR DESCRIPTION
**Pull request by sbzlzh**
Partial translation using new bin, deepl, google ai.

### CODE REVIEW

**Comment by Freilichtbuehne** [comment]
@sbzlzh thank you for your pull request. Have you tried using this language ingame?



Or is this a problem only on my system?

**Comment by sbzlzh** [comment]
It shows up correctly on my server and doesn't show up like yours, I'll try again sometime.

**Comment by Freilichtbuehne** [comment]
No, that's okay then. I will merge your translation. Thank you again.

**Comment by sbzlzh** [comment]
image
It shows up on the server like this

**Pull request merged**
